# Generated by Django 6.0.2 on 2026-04-03 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccessAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('employee_created', 'Сотрудник создан'), ('invitation_issued', 'Приглашение выпущено'), ('invitation_revoked', 'Приглашение отозвано'), ('activation_succeeded', 'Активация успешна'), ('activation_failed', 'Активация неуспешна'), ('access_reset', 'Доступ сброшен'), ('employee_deactivated', 'Сотрудник деактивирован')], max_length=32, verbose_name='Тип события')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_access_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='employees.employeeinvitation', verbose_name='Приглашение')),
            ],
            options={
                'verbose_name': 'Событие аудита доступа',
                'verbose_name_plural': 'События аудита доступа',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='employee_audit_type_idx'), models.Index(fields=['employee', 'created_at'], name='employee_audit_emp_idx')],
            },
        ),
    ]
