# Generated by Django 6.0.2 on 2026-04-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeaccessauditevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['email'], 'permissions': [('manage_employee_access', 'Can manage employee invitations and access state'), ('view_employee_access_audit', 'Can view employee access audit log')], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
