"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project root .env file for local runs.
load_dotenv(BASE_DIR.parent / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

LOCAL_ENVIRONMENT = "local"
PRODUCTION_ENVIRONMENT = "production"
DJANGO_ENV = os.getenv("DJANGO_ENV", LOCAL_ENVIRONMENT).strip().lower() or LOCAL_ENVIRONMENT
INSECURE_SECRET_KEY_VALUES = {
    "unsafe-local-development-key",
    "replace-with-a-long-random-secret",
}


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def get_debug_setting(environment):
    if environment != LOCAL_ENVIRONMENT:
        return False
    return env_bool("DJANGO_DEBUG", default=True)


def get_allowed_hosts(environment, debug_enabled):
    allowed_hosts = [
        host.strip()
        for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
        if host.strip()
    ]

    if allowed_hosts:
        return allowed_hosts

    if environment == LOCAL_ENVIRONMENT and debug_enabled:
        return ["127.0.0.1", "localhost"]

    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS must be configured outside local development."
    )


def get_secret_key(environment):
    secret_key = (os.getenv("DJANGO_SECRET_KEY") or "").strip()
    if secret_key and (
        environment == LOCAL_ENVIRONMENT
        or secret_key not in INSECURE_SECRET_KEY_VALUES
    ):
        return secret_key

    if environment == LOCAL_ENVIRONMENT:
        return "unsafe-local-development-key"

    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be configured outside local development and must not use placeholder or fallback values."
    )


def get_security_settings(environment):
    if environment != PRODUCTION_ENVIRONMENT:
        return {
            "SECURE_SSL_REDIRECT": False,
            "SESSION_COOKIE_SECURE": False,
            "CSRF_COOKIE_SECURE": False,
            "SECURE_PROXY_SSL_HEADER": None,
        }

    return {
        "SECURE_SSL_REDIRECT": True,
        "SESSION_COOKIE_SECURE": True,
        "CSRF_COOKIE_SECURE": True,
        "SECURE_PROXY_SSL_HEADER": ("HTTP_X_FORWARDED_PROTO", "https"),
    }


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret_key(DJANGO_ENV)

# SECURITY WARNING: don't run with debug turned on outside local development!
DEBUG = get_debug_setting(DJANGO_ENV)
ALLOWED_HOSTS = get_allowed_hosts(DJANGO_ENV, DEBUG)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'analogs',
    'counterparties',
    'employees',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = "employees.Employee"
AUTHENTICATION_BACKENDS = [
    "employees.auth_backends.EmployeeAuthenticationBackend",
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

SECURITY_SETTINGS = get_security_settings(DJANGO_ENV)
SECURE_SSL_REDIRECT = SECURITY_SETTINGS["SECURE_SSL_REDIRECT"]
SESSION_COOKIE_SECURE = SECURITY_SETTINGS["SESSION_COOKIE_SECURE"]
CSRF_COOKIE_SECURE = SECURITY_SETTINGS["CSRF_COOKIE_SECURE"]
SECURE_PROXY_SSL_HEADER = SECURITY_SETTINGS["SECURE_PROXY_SSL_HEADER"]

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/analogs/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
EMPLOYEE_INVITATION_TTL = timedelta(hours=24)
EMPLOYEE_AUTH_RATE_LIMITS = {
    "login": {
        "attempts": 5,
        "window_seconds": 300,
        "block_seconds": 300,
    },
    "password_setup": {
        "attempts": 5,
        "window_seconds": 300,
        "block_seconds": 600,
    },
    "invitation_reissue": {
        "attempts": 10,
        "window_seconds": 3600,
        "block_seconds": 900,
    },
}
