# Generated by Django 6.0.2 on 2026-03-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
    ]
